In [1]:
# Import necessary libraries
import numpy as np
from sklearn.linear_model import LinearRegression

# Define the input and output variables
X = np.array([2, 4, 5, 7, 8, 9, 10, 11, 12, 15]).reshape((-1, 1))
y = np.array([60, 75, 80, 85, 90, 92, 95, 96, 97, 100])

# Create the linear regression object
model = LinearRegression()

# Fit the model to the data
model.fit(X, y)

# Print the coefficients of the linear regression equation
print('Intercept:', model.intercept_)
print('Slope:', model.coef_)

# Predict the test grade for a student who studied for 6 hours
hours_studied = np.array([6]).reshape((-1, 1))
predicted_grade = model.predict(hours_studied)
print('Predicted test grade:', predicted_grade)


Intercept: 62.59172019985725
Slope: [2.9407566]
Predicted test grade: [80.23625981]


In [3]:
X = np.array([2, 4, 5, 7, 8, 9, 10, 11, 12, 15])
# .reshape((-1, 1))

X

array([ 2,  4,  5,  7,  8,  9, 10, 11, 12, 15])

In [4]:
type(X)

numpy.ndarray

In [5]:
X = np.array([2, 4, 5, 7, 8, 9, 10, 11, 12, 15]).reshape((-1, 1))

X

array([[ 2],
       [ 4],
       [ 5],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [15]])

In [12]:
model.predict(np.array([2]).reshape([-1,1]))

array([68.4732334])

In [13]:
from sklearn.metrics import mean_squared_error

# Predict the test grades
y_pred = model.predict(X)

# Calculate the mean squared error
mse = mean_squared_error(y, y_pred)
print('Mean squared error:', mse)

Mean squared error: 16.24082798001428


In [14]:
y

array([ 60,  75,  80,  85,  90,  92,  95,  96,  97, 100])

In [15]:
y_pred

array([ 68.4732334 ,  74.35474661,  77.29550321,  83.17701642,
        86.11777302,  89.05852962,  91.99928622,  94.94004283,
        97.88079943, 106.70306924])